project:
  type: website
  output-dir: _site
  render:
  - "*.qmd"
  - "!scripts/Analysis/Analysis_Oskar.Rmd"

website:
  title: "Digital Competence in the Biological Sciences"
  navbar:
    logo: assets/images/course-logo.png
  sidebar:
    contents:
      - index.qmd
      - section: "Course Days"
        contents:
          - days/day01.qmd
          - days/day02.qmd
          - days/day03.qmd
          - days/day04.qmd
          - days/day05.qmd

format:
  html:
    theme: cosmo
    toc: true
    
execute:
  freeze: auto